### ISSUE TITLE
ARBITRUM - Swapr BADGER / WETH swprLP

### ISSUE THREAD

**Issue by shuklaayush** [Badger-Finance/badger-strategies#19]
# Strategy Review
Take BADGER / WETH swprLP, stake in stakingContract
100% swpr rewards sent to badgerTree as weth/swapr helper vault token

### Code Link 
https://github.com/shuklaayush/arbitrum-badger-eth-swapr/releases/tag/v0.2.1

The strategy is similar to https://github.com/Badger-Finance/badger-strategies/issues/13 with different contract/token addresses and 100% emissions.

Here's a diff with the upstream repo
https://github.com/GalloDaSballo/arbitrum-wbtc-eth-swapr/compare/main...shuklaayush:v0.2.1

## Deployed Contract (If present)
See [below](https://github.com/Badger-Finance/badger-strategies/issues/19#issuecomment-942357808)

## Reviews
- [x] @GalloDaSballo 
- [ ] @sajanrajdev  
- [ ] @dapp-whisperer  

## Test Checks (screenshot of all test passing)
![image](https://user-images.githubusercontent.com/27727946/137974269-99ac7eb9-902c-4da2-adbb-b1c7eb75c4a2.png)

## TODO
- [x] Approve strategy to deposit in helper vault https://github.com/Badger-Finance/badger-strategies/issues/16
- [x] Harvest
- [x] `setStakingContract` before going to production
- [x] Prod wire-up
- [x] Add guestlist/caps
- [x] Delegate `governance` to dev-multisig

**Comment by shuklaayush** [comment]
Added to registry
https://arbiscan.io/tx/0x2f069c0d77c4bc190cc998853cd1adbcf2571eb98ee1712f31862d8c45413e98

**Comment by GalloDaSballo** [comment]
Update Strategy:
```
>>> c = Controller.at("0x746FAc0bb04Ca854334AD9cc75C96B60616D4475")
>>> v = SettV3.at("0xE9C12F06F8AFFD8719263FE4a81671453220389c")
>>>  t = ERC20Upgradeable.at(v.token())
>>> new_strat = MyStrategy.at("0x22F340C2604Dc1cDBe26caC5838Ea9EBC8862a46
>>> c.approveStrategy(t, new_strat, {"from": a[-1]})
Transaction sent: 0xb0110fee7c3c5aace6495131eadcb5b561b1a52ea76ec31c5c5c69c80129b212
>>> c.setStrategy(t, new_strat, {"from": a[-1]})
Transaction sent: 0xf06b933288c694b44ec623638e08969a44aa81562100de2ab6c35baa7743aa9c
```
@shuklaayush

**Comment by shuklaayush** [comment]
Transferred ownership of guestlist to tech-ops:
`0x292549e6bd5a41ae4521bb8679ada59631b9ed4c`
![image](https://user-images.githubusercontent.com/27727946/140740528-165ddcf3-7a74-4d65-a754-0ff9c655ee77.png)
https://arbiscan.io/tx/0xe75e2b672436e86416fbe2f6c9f484a8ed1415a2b3511a726ca6ad01f3ab4ca2

**Comment by shuklaayush** [comment]
Upgrade to fix `withdrawAll` when no pending rewards
https://github.com/shuklaayush/arbitrum-badger-eth-swapr/tree/v0.3

Diff: https://github.com/shuklaayush/arbitrum-badger-eth-swapr/compare/v0.2.1...v0.3#diff-f8da72ae916d33dc152fcb1f98526aee546d93502123f04280e848bc82e20532

@GalloDaSballo Please review

**Comment by shuklaayush** [comment]
Old logic: [0x144a2bb88ae708d5a0793fb0166f17d7b2accaf3](https://arbiscan.io/address/0x144a2bb88ae708d5a0793fb0166f17d7b2accaf3#code)
New logic: [0xdD2f894375CdC8E4E574F0ccB9B65D617CEafee5](https://arbiscan.io/address/0xdD2f894375CdC8E4E574F0ccB9B65D617CEafee5#code)
