### ISSUE TITLE
ARBITRUM - Swapr ibBTC/WETH swprLP

### ISSUE THREAD

**Issue by shuklaayush** [Badger-Finance/badger-strategies#24]
# Strategy Review
Take ibBTC / WETH swprLP, stake in stakingContract
100% swpr rewards sent to badgerTree as weth/swapr helper vault token

### Code Link 
https://github.com/shuklaayush/arbitrum-ibbtc-eth-swapr/releases/tag/v0.1.1

Same as #19 with different addresses

Here's a diff with the badger/weth strat
https://github.com/shuklaayush/arbitrum-ibbtc-eth-swapr/compare/3a03640f1be70c3e3f1fceff60c2eb49d28aa038...v0.1.1

## Deployed Contract (If present)
https://github.com/Badger-Finance/badger-strategies/issues/24#issuecomment-951998192

## Reviews
- [ ] @GalloDaSballo 
- [ ] @sajanrajdev  
- [ ] @dapp-whisperer  

## Test Checks (screenshot of all test passing)
![image](https://user-images.githubusercontent.com/27727946/138866735-057ac662-971a-4b9c-a362-c76cb999fbb7.png)

## TODO
- [x] Approve strategy to deposit in helper vault https://github.com/Badger-Finance/badger-strategies/issues/16
- [x] Harvest
- [x] `setStakingContract` before going to production
- [x] Prod wire-up
- [x] Add guestlist/caps
- [x] Delegate `governance` to dev-multisig

**Comment by shuklaayush** [comment]
Transferred ownership of guestlist to tech-ops:
`0x292549e6bd5a41ae4521bb8679ada59631b9ed4c`
![image](https://user-images.githubusercontent.com/27727946/140740676-efe1f7e4-96ce-4eb1-bfce-a9e33613220a.png)
https://arbiscan.io/tx/0x917b5faa2f4f10529f78a4c26f1ad5ff3aa93edc94eaa25775dd76a575505c72

**Comment by shuklaayush** [comment]
Upgrade to fix `withdrawAll` when no pending rewards
https://github.com/shuklaayush/arbitrum-ibbtc-eth-swapr/tree/v0.3

Diff: https://github.com/shuklaayush/arbitrum-ibbtc-eth-swapr/compare/v0.1.1...v0.3#diff-f8da72ae916d33dc152fcb1f98526aee546d93502123f04280e848bc82e20532

@GalloDaSballo Please review

**Comment by shuklaayush** [comment]
Old logic: [0x496372872170654f1768fEe618CC37e8e3022972](https://arbiscan.io/address/0x496372872170654f1768fEe618CC37e8e3022972#code)
New logic: [0x89C5A4ef2532a7229A750908CD278aa2491b4C46](https://arbiscan.io/address/0x89C5A4ef2532a7229A750908CD278aa2491b4C46#code)
